sudo: false
cache:
  bundler: true

stages:
  - compile
  - test
  - name: taggear
    if:
    - branch = master
    - type = push
  - name: deploy dev
    if:
    - branch = master
    - type = push
  - name: deploy homolog
    if:
    - branch = homolog
    - type = push

jobs:
  include:
    - stage: compile
      language: ruby
      rvm:
      - 2.4
      addons:
        apt:
          packages:
          - libcurl4-openssl-dev
      script: bundle exec rake test
    - stage: test
      sudo: required
      services:
        - docker
      script:
        - bundle exec rake build
        - docker-compose up -d site
        - ./scripts/smoke-test.sh http://localhost:80
    - stage: taggear
      script: skip
    - stage: deploy dev
      addons:
        apt:
          packages:
          - lftp
      before_deploy:
        - bundle exec rake build
      deploy:
        provider: script
        script: scripts/deploy-ftp.sh
        skip_cleanup: true
        on:
          branch: master
      after_sucess:
        - ./scripts/smoke-test.sh http://vagalume.silverwolf.com.br

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DEBUG=1
  - secure: UphghT5AlxN+AbuEO5aXrQm7Nb7Ticf9bxGeB6iEKvLLTf8iwIpXF8/l2dwbVo9NbbLh6DsBCDDtwfb690G5Rc1Js7+6U0V2PwULUFBwCXw5BdNiS2FW+8vKwJMTorb4FLNcriuH6QDUXM7LolqrETLg/a2QKdxqxuN6cxJrVygbv95iZxE2oeDKksHobzJ6jIfRnOViUSAmt+0O77ou9HvrqwMU6BLciY0NftHJePLcJpTmsMc7SgLpjveJBvE8sKjFR3+OqEfOhG4D/b2gKif186Br3qRRH4YOqu70zrW75jltjB3L4FUq5uiHWnjbvpVgb84/ESj+SgHeY/VwjoITey9jR7UiGldG23ojazCeqNjX1rz0wBN/fHh8rzpr/3aU3LSAWi7bU0zCkxXYkJSZee2AG7rvPiX0rcJ2L2IdC2o2w64ca71XSQi+n7niSzv0pGPA1WjDZW6SCby6L3+UDUNJAl6WUKBaB/9ujxE1RNDt4PkNfSUhT3qHuqtnJFeqZPOW+/i4BkzRjVAn3n8Zasv0FJTWt6Bscb0F/oTf8bVGZIfC2UDoZSc/no3eX/n9ios0AmmqkTHBSAev3MevniTcxF2XMzCwT29WAP6tRjtTyvvxysQ4T0Ft0gpnxJkMUpTzkv43QZNaxt4L0pNjlgpEYF2dCiF3HpL7rMM=
  - secure: ENbTkhBXx/IWTkKMWRUw61n3Dzuyy1QdmObhGjloO02clCJF6w07+22k2kwsYizJSqSiYrG18G+1OCpFj2aCtJPy15eZLc9TiZc3ZqyqSi2FNbxty02463VRurQ+F8LpiugcdAjBFkBLhOogDPp1wXk5qyEkfGY6GDBTAnDJMDNHrVxNOFWS9Ezj4dvBo/r0GoQcL8f1o8K81OUKRgGJiVNrLi9zR49gNInwnqJgi57Jv4f8Ik6cMGjhkV7nZkzp4BedGlwM2aEfxdGRmo1p6IPXixI7Ibh6pEtLAahWWs71hJchT8dnRSTpEUrsN81et4zCCLPs2dkbhrEtC9PVhAjVxLOyDyOW6sWevnAfGCLTjVybAvMlRqq4cWCsYEJpei6faaeExn9wkiVTG0a+qnRgACl/huBRaPigGv0tT+ZXw8FTHYFP/88g99Q5WgnmqpFJ0cOd/vqDf1zeYFeAiQXunQ8TLu6xdAnE4DTMSMBXZZU6swGAtr1speqISXOQvQi1JG0naO2HFKdAoizjwC8kIi9uC/HOlwvvlbFwzkKDVt1qSU2CpMSgqLI8/1NRhjw4Sbx2NAFdyGOkvLwvvAVSzd/snlMqwdhlZ1F2Kbd2Z3nkFM9AmQ5+bYNbPOiNR0C5sm/vWvXTK3wvXabHhAw/pUXGIAbRuO22ueT3Prs=
  - secure: mGVQvcTEOJ5m3d4FRKxZ9qJPEyNLuFBCPSmklGmEUziibdzFfrpf6l4faHwsWBFE46BzQE/dXcbymPrXUF/lxLtuX/+vMKjQ8mABt1fF2qYTcf8GjCqTRpORZ42rlcP30cFQ0t8APonB7fo5FvNUo6HlbSmMQBGDm0CKSU/Xz1LezFWSJSuKdEvzc8x4J+KwQtD6PqEkE3qQcdS0XzU6T/pwr+v1OZHOrGF/gkVfKv0t4x8yriycdW4xBv0ado9DIXYeErq5TnKQxiFbX21WGmotUHc4Doc6sYCu+F0QsPkdrUgw2CUT1oqSPpAyhxU8qzyKZj/NglQMhwvfykfmIPRBsYMyDMBiT8we0W/e9+Zh2YoIrdmhkf2yJf19tBCG19LyUEVlDDK2AshvOnqxf5hoPv5IWrrN79HCuaMQAgkqIANlW/jWi8OWFqBdkCMseOHpo+Uk4BvefOYzD9Hhg/ccDAEwT/faabiDR0zEHNLKjgScWPhr9rSKxG06e15EC6NYFWQQtJM8K4z/uoT4oBdPAp5NxpgOjf9CgrDlTSFVpGAi0mIw60YMpNrruLnvtEXPxKf0b/HpQ2QVVe31mhf+dwVxwREqpdQrKpLOnstYvioGKO7Iukk0xjjKA/rHZSKDAm5cUnxHsq6+trb2odrVV6ydBdXVxCWCa4zjaXU=
