sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - lftp
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: GJpNt/uVuYjMDqGILaxsRVN7flYWpPYaqeY9rDIp/tW3p5NAzA8GfN9ge6V0YAt3SIqtEzcwXxMJm+WzY7ASkuuIakvp9TfJVVYCZzVljParyIxToS0UXgIKHaZG6RrOhwxAqtyGUPlxhRCmxnzHrEdtjpNZmWpFeOG8243GXWoO1m7wmIlOAEiHN6KjfkSpCVcCuxm26uGlYx4GISx366Vsx4QIQrpNeWX7lY+/AyvwvlNm4ZlRK4oarUXjONt+0UHAig4V5Oi7tvNSDLtOV6v2lY5/2jFnL2osxAr4nC/EJdwHZJgdmayxM+fAEk3JeR+bPC5tlDJ7+PUvKbywN5Z/G2torC7PHIlu1JizGs4zN+LW/z/bhEdpcxoQCvb78xYkYeAdRmDix4/lMxXu31RSKW92gqg8kNhnqqwsNDqtXEBC7xZnb5j+tpWvl/mOvusHAvBDF/olDN+F/GovMro2zRvcRmF5vfh3CVxiheA1UMkExxlrrptE8nuKoLigUlNpa4gFrxFMnwS2uZthkWEeuQmGa36vdovhuhRRnvwfJ7+GZ4rpEeIiGv5/po3N0uIK4svtLsBD/q7ALJccr1xOZqAV5Or7AqmizThNZDJp81X7FzVlwa6HIpZ8Yfvr3H2+aymLJPQGUrCBgLaENRkjgzqbpa1WmjD2d5MC9fY=
  - secure: nFKQkeZKuJlV7BW82hfT8tZlDMTt3PhnRFYAMIH6k4rKHARtVrlkeK4CcKzkJq9LCsLkLZ7ZGkJ7NFMZ7T60StGB2I0OIG8odmHs6HbaLiKttxjBhq64rkJROlV1sM6jzGvd9Z85JC+ThFk2Dm5OUM7TnFzEIkooi/5vEGho4+m9W7+TWWtlmvlZlbGAWzcpKzyvkIGQ0R/iykHim3aqekR0FzbIrDWJ3oF8iiNf5A2jwydBu3PDtt1vammFvfSJsMUV4cPvVoswB/MwanJLWO4N97EWGS7VVjVkjMQM1iKdFTJWfzkP/ODegb49fwqGtD5khAD2FS6eyFnqH853hsujWVJ4hLL+ESDp2j5Ds8bbnumGU1p5zuAbaf69YhJWl5vxCWnKgACquJooTT1/n7SYLjJo0GvCf4yp784d4jSxgeHSifKsOWkJHz/+/Ka3SFEc/0Rp2XYVI44KHZEtWGdISEWnlVv0/zhdg0DovN8lJOS/VZoR2eHd69ZGxARltJFaMo6onTRQ6tRp5tr2U9L2LFiuSmpjRNPP9R7C1At4UrmpkLKCyDs0KiiRA5XFPb0Nom5lW7PlrWDP4UGyFGFfHbNbRrexDztN8RH0S5QalUP1zZ0syWsKa6MgOpZz5xCD1fvyc1qxpb7GYiSdFZZ/2elnzTyV+16em1bd6CM=
  - secure: XWkVyyZi5gSNPSVBWiIhHYnGTWTdQsUH+snmFq58Ehl1EjPLPtObkSu9HWKLVmzkrwfvos1TbUSeXcUqqbzKvg2RU1eHNwyCSeWPl4rvYcUpwOM3hfbk2dlyYlsx9W4jnmvf1HQl8cklfF3DVD+nvV7a6Qv/TTomYBQEZdp/7hq/fPkRw2zT9e+BvvZgGF7Nragrwuyzl75ysFgPg5LGhngFQZVrE/d9UA3sgNEDRsN7q9X1bjz7qnjlNktVKAISNQd2k1mv6ycXlztE0EAn31xq1pWnK1JgqL88iFuudtGu9/suo4ElbnGHJkbPdyJy0U2uEw6HZ0ibmKmYlLMOfe6tFfvFUiv4r/d4uksmB6c7VxvlQGLYphxSoBo8M4BHEXuUkuPhlfjV7eY/F/6mBzaAM3pvdZCUpOX/Hvsd+tia8YiMMhU1sU5uFtnsr1y3wv2NN2ZsumI/qsxz0miHz8ATcV4X5v2VjG6xMxHf7HhpHRDUMGGMFZZkhvOqTAg4DA5lGc1sz9/rgmdpQpYfccULWIx3gsZ/LBOccDD2yTOFqw2wuWUTc2ZT3QCaGk35YXFdcCgHrcCP9R7qnbJ1qZUCl7RoXDJb76sXrimbv4vQif/qKzkMPQ6tdEfEzuRZJRXzdNEcbqB3xFampzzkkus8MU2uL0W63s5CWt3zSK8=
language: ruby
rvm:
  - 2.3.3
install:
  - bundle install
  - bundle exec jekyll build
after_success:
  - chmod 755 scripts/deploy-ftp.sh
  - sh scripts/deploy-ftp.sh
