sudo: false
exclude: [vendor]
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
language: ruby
rvm:
  - 2.3.3
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
install:
  - bundle install
  - bundle exec jekyll build
