version: '3'
services:
  server:
    command: ["jekyll", "serve", "-H", "0.0.0.0"]
    image: jekyll/jekyll:3.5
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
  site:
    build: .
    image: vagalume
    ports:
      - 80:80