version: '3'
services:
  site:
    command: ["jekyll", "serve", "-H", "0.0.0.0"]
    image: jekyll/jekyll:3.5
    volumes:
      - $PWD:/srv/jekyll
      - /usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      - 80:4000
